spring:
  application:
    name: blog
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: ZAKRI
    password: 'jw52U[6^K/8v'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: false
      sort:
        sort-parameter: sort
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
      file-size-threshold: 2KB

server:
  tomcat:
    max-swallow-size: 100MB

logging:
  level:
    org.springframework.data.web.PageableHandlerMethodArgumentResolver: ERROR
    org.springframework.data.web.config.SpringDataJacksonConfiguration: ERROR
